env: "local"

server:
  host: "localhost"
  port: "8000"

db:
  username: "postgres"
  host: "localhost"
  port: "5432"
  dbname: "msikanov"
  sslmode: "disable"
  password: "1474"

cors:
  origins: [
    "http://localhost:4200"
  ]
  methods: [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "HEAD",
    "OPTIONS",
    "PATCH"
  ]
  headers: [
    "*"
  ]